spring.application.name=task-streak-backend
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/taskstreak
spring.data.mongodb.auto-index-creation=true

jwt.secret=9a6747f3b64c8c0e75e3d499cdd9f733e3876e5d8ecd5fc2f3a61e0657b98764
jwt.expiration=86400000

app.daily-reminder.cron=0 0 20 * * *
app.weekly-streak.cron=0 0 0 * * MON

logging.level.com.taskstreak=INFO
